blob_detector:
  blob_min: 
  - 39
  - 81
  - 71
  blob_max: 
  - 75 
  - 255
  - 255
jessiarm_speed:
  SCAN_SPEED: 0.04

# blue_min = (55,40,0)
# blue_max = (150, 255, 255)  

# white_min = (16, 0, 66)
# white_max = (133, 251, 255)

# pink_min = (135, 41, 95)
# pink_max = (255, 196, 255)

# green_min = (39, 81, 71)
# green_max = (75, 255, 255)

# orange_min = (7, 109, 50)
# orange_max = (76, 218, 234)