#turn left or right of base
MOTOR0_ZERO = 380
MOTOR0_HOME = 380
MOTOR0_OFF = MOTOR0_HOME
YAW_MIN = 270
YAW_MAX = 490

#forward or backward
#roll, 3 DOF
ROLL_TOTAL_MAX = 300
ROLL_TOTAL_MIN = -100

MOTOR1_ZERO = 520
MOTOR1_HOME = 450
MOTOR1_OFF = 540
MOTOR1_MIN  = MOTOR1_HOME
MOTOR1_MAX  = MOTOR1_OFF
MOTOR1_DIF_MIN = (MOTOR1_MIN - MOTOR1_HOME)
MOTOR1_DIF_MAX = (MOTOR1_MAX - MOTOR1_HOME)

MOTOR2_ZERO = 380
MOTOR2_HOME = 460
MOTOR2_OFF = 540
MOTOR2_MIN  = MOTOR2_HOME
MOTOR2_MAX  = MOTOR2_OFF
MOTOR2_DIF_MIN = (MOTOR2_MIN - MOTOR2_HOME)
MOTOR2_DIF_MAX = (MOTOR2_MAX - MOTOR2_HOME)

MOTOR3_ZERO = 380
MOTOR3_HOME = 460
MOTOR3_OFF = 540
MOTOR3_MIN  = MOTOR3_HOME
MOTOR3_MAX  = MOTOR3_OFF
MOTOR3_DIF_MIN = (MOTOR3_MIN - MOTOR3_HOME)
MOTOR3_DIF_MAX = (MOTOR3_MAX - MOTOR3_HOME)

#gripper rotation
MOTOR4_ZERO = 400
MOTOR4_HOME = MOTOR4_ZERO
MOTOR4_OFF = MOTOR4_ZERO
PITCH_MIN = 270
PITCH_MAX = 490

#gripper open/close
GRIPPER_OPEN = 240        
GRIPPER_CLOSE = 380
GRIPPER_ZERO = GRIPPER_OPEN
GRIPPER_HOME = GRIPPER_OPEN
GRIPPER_OFF = GRIPPER_OPEN
GRIPPER_MIN = GRIPPER_OPEN       
GRIPPER_MAX = GRIPPER_CLOSE
