#servo motor full pulse
MIN_PULSE_WIDTH = 220
MAX_PULSE_WIDTH = 540
#turn left or right of base
MOTOR0_ZERO = 380
MOTOR0_HOME = 380
MOTOR0_OFF = MOTOR0_HOME
YAW_MIN = 270
YAW_MAX = 490
MOTOR0_PICKUP1 = YAW_MIN
MOTOR0_PICKUP2 = YAW_MAX

#forward or backward
#roll, 2 DOF
ROLL_TOTAL_MAX = 120
ROLL_TOTAL_MIN = -120

MOTOR1_ZERO = 360
MOTOR1_HOME = 360
MOTOR1_PICKUP = (MOTOR1_HOME - 10)
MOTOR1_OFF = MOTOR1_HOME
MOTOR1_MIN  = 270
MOTOR1_MAX  = 460
MOTOR1_DIF_MIN = (MOTOR1_MIN - MOTOR1_HOME)
MOTOR1_DIF_MAX = (MOTOR1_MAX - MOTOR1_HOME)

MOTOR2_ZERO = 380
MOTOR2_HOME = 550
MOTOR2_PICKUP = (MOTOR2_HOME - 30)
MOTOR2_OFF = (MOTOR2_HOME + 20)
MOTOR2_MIN  = (MOTOR2_HOME - 60)
MOTOR2_MAX  = MOTOR2_OFF
MOTOR2_DIF_MIN = (MOTOR2_MIN - MOTOR2_HOME)
MOTOR2_DIF_MAX = (MOTOR2_MAX - MOTOR2_HOME)

MOTOR3_ZERO = 380
MOTOR3_HOME = 560
MOTOR3_PICKUP = (MOTOR3_HOME - 20)
MOTOR3_OFF = (MOTOR3_HOME + 20)
MOTOR3_MIN  = (MOTOR3_HOME - 60)
MOTOR3_MAX  = MOTOR3_OFF
MOTOR3_DIF_MIN = (MOTOR3_MIN - MOTOR3_HOME)
MOTOR3_DIF_MAX = (MOTOR3_MAX - MOTOR3_HOME)

#gripper rotation
MOTOR4_ZERO = 380
MOTOR4_HOME = MOTOR4_ZERO
MOTOR4_OFF = MOTOR4_ZERO
PITCH_MIN = 270
PITCH_MAX = 490

#gripper open/close
GRIPPER_OPEN = 240        
GRIPPER_CLOSE = 380
GRIPPER_ZERO = GRIPPER_OPEN
GRIPPER_HOME = GRIPPER_OPEN
GRIPPER_OFF = GRIPPER_OPEN
GRIPPER_MIN = GRIPPER_OPEN       
GRIPPER_MAX = GRIPPER_CLOSE

#yolo_chase or blob_chase
PICTURE_SIZE_X = 640.0
PICTURE_SIZE_Y = 480.0
CALIBPICTURE = 0.00
#please change this class for detection

#steering sensitivity parameter
DIR_TO_STEER = -1.0
Kp = 0.2

MOTOR0_RANGE = (YAW_MAX -YAW_MIN)
IN_RANGE_MIN = -0.02
IN_RANGE_MAX = 0.02
